
spring:
  datasource:
    clickhouse:
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://mac.zjf:8123/default
      username: default
      password:
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000

#pagehelper:
#  helperDialect: clickhouse
#  auto-runtime-dialect: true